[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "inspect_flexible_tasks"
version = "0.1.0"
dependencies = [
    "inspect_ai",
    "inspect_evals"
]

[tool.setuptools]
packages = ["inspect_flexible_tasks"]

[project.entry-points."inspect_ai.extensions"]
inspect_flexible_tasks = "inspect_flexible_tasks.__init__"
